name: QSRRWorldGuardAddon
main: com.mcsunnyside.qsworldguard.QSRRWorldGuardAddon
version: 0.0.2-SNAPSHOT
authors: [Ghost_chu]
description: QSRR's WorldGuard Addon
depend: [QuickShop,WorldGuard]

api-version: 1.13