name: QSRRWorldGuardAddon
main: com.mcsunnyside.qstowny.QSRRWorldGuardAddon
version: 0.0.1-SNAPSHOT
authors: [Ghost_chu]
description: QSRR's WorldGuard Addon
depend: [QuickShop,WorldGuard]

api-version: 1.13